### ISSUE TITLE
[FEATURE] Image support for gencli 

### ISSUE THREAD

**Issue by itsBaivab** [Pradumnasaraf/gencli#10]
### Description

What if we can insert image with our queries like 
``` sh
gencli search image <img-path> <Queary>
```

**Comment by Pradumnasaraf** [comment]
Great idea, let me try locally and see how it responds!

Thank you for the issue!

**Comment by Pradumnasaraf** [comment]
Hey @itsBaivab, 

I have raised a PR for that #11 let me know what you think feel free to add suggestions or changes
